definitions:
  cross.CrossData:
    properties:
      chain:
        example: ""
        type: string
      chain_and_gas_limit:
        example: ""
        type: string
      height:
        example: 81507414
        type: integer
      is_memoized:
        example: false
        type: boolean
      log_index:
        example: 1
        type: integer
      order_id:
        example: ""
        type: string
      timestamp:
        example: 1767097427
        type: integer
      topic:
        example: ""
        type: string
      tx_hash:
        example: ""
        type: string
    type: object
  cross.CrossSet:
    properties:
      dest:
        allOf:
        - $ref: '#/definitions/cross.CrossData'
        description: target Chain Transactions
      map_dest:
        allOf:
        - $ref: '#/definitions/cross.CrossData'
        description: map dest Transactions
      now:
        type: integer
      order_id:
        type: string
      relay:
        allOf:
        - $ref: '#/definitions/cross.CrossData'
        description: relay chain transaction
      relay_signed:
        allOf:
        - $ref: '#/definitions/cross.CrossData'
        description: relay signed transaction , The front end ignores this field.
      src:
        allOf:
        - $ref: '#/definitions/cross.CrossData'
        description: source chain transaction
      status:
        $ref: '#/definitions/cross.StatusOfCross'
      status_str:
        type: string
    type: object
  cross.StatusOfCross:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    format: int64
    type: integer
    x-enum-varnames:
    - StatusOfInit
    - StatusOfPending
    - StatusOfSend
    - StatusOfCompleted
    - StatusOfFailed
  main.ChainHeightResponse:
    properties:
      height:
        type: string
    type: object
  main.ChainOrderIdResponse:
    properties:
      height:
        type: string
      set:
        items:
          type: string
        type: array
    type: object
  main.CrossSignelResponse:
    properties:
      data:
        $ref: '#/definitions/cross.CrossSet'
    type: object
  main.PendingTxResponse:
    properties:
      txs:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  description: tss跨链服务api
  title: compass-tss-api
  version: "1.0"
paths:
  /cross/chain/height:
    get:
      consumes:
      - application/json
      description: 根据 chainId 获取扫描高度
      parameters:
      - description: chainId
        in: query
        name: chainId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ChainHeightResponse'
        "400":
          description: bad request
      summary: 获取当前扫描有交易的最高高度
      tags:
      - 交易记录
  /cross/chain/height/orders:
    get:
      consumes:
      - application/json
      description: 根据 chainId 获取扫描交易集合
      parameters:
      - description: "1"
        in: query
        name: chainId
        required: true
        type: string
      - description: "12245"
        in: query
        name: height
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ChainOrderIdResponse'
        "400":
          description: bad request
      summary: 获取高度对应的交易集群
      tags:
      - 交易记录
  /cross/height/range/txs:
    get:
      consumes:
      - application/json
      description: 根据高度区间获取交易列表
      parameters:
      - description: chainId
        in: query
        name: chainId
        required: true
        type: string
      - description: startHeight
        in: query
        name: startHeight
        required: true
        type: string
      - description: endHeight
        in: query
        name: endHeight
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.CrossSignelResponse'
            type: array
        "400":
          description: bad request
      summary: 根据高度区间获取交易列表
      tags:
      - 交易记录
  /cross/order:
    get:
      consumes:
      - application/json
      description: 通过orderId获取交易记录
      parameters:
      - description: orderId
        in: query
        name: orderId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.CrossSignelResponse'
        "400":
          description: bad request
      summary: 通过orderId获取交易记录
      tags:
      - 交易记录
  /cross/pending/tx:
    get:
      consumes:
      - application/json
      description: 根据 chainId 获取pending的交易列表
      parameters:
      - description: chainId
        in: query
        name: chainId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PendingTxResponse'
        "400":
          description: bad request
      summary: 获取pending的交易列表
      tags:
      - 交易记录
  /cross/tx:
    get:
      consumes:
      - application/json
      description: 通过 txHash 获取交易记录
      parameters:
      - description: txHash
        in: query
        name: tx
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.CrossSignelResponse'
        "400":
          description: bad request
      summary: 通过 txHash 获取交易记录
      tags:
      - 交易记录
swagger: "2.0"
